# Generated by Django 5.2.1 on 2025-05-28 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duracion_dias', models.IntegerField()),
                ('acceso_piscina', models.BooleanField(default=False)),
                ('acceso_clases_grupales', models.BooleanField(default=False)),
                ('acceso_personal_trainer', models.BooleanField(default=False)),
            ],
        ),
    ]
